services:
  reservations:
    build: 
     context: .
     dockerfile: ./apps/reservation/DockerFile
     target: development
    command : npm run start:dev  reservation
    ports:
      - '3000:3000'
    volumes:
     - .:/user/src/app
    env_file:
      - ./apps/reservation/.env
  auth:
    build: 
      context: .
      dockerfile: ./apps/auth/DockerFile
      target: development
    command : npm run start:dev  auth
    ports:
      - '3001:3001'
    volumes:
     - .:/user/src/app
    env_file:
      - ./apps/auth/.env
  payments:
    build: 
      context: .
      dockerfile: ./apps/payments/DockerFile
      target: development
    command : npm run start:dev  payments
    ports:
      - '3004:3004'
    volumes:
     - .:/user/src/app
    env_file:
      - ./apps/auth/.env
  mongo:
    image: mongo
     