FROM node:18.14.0-alpine As development

WORKDIR   /user/src/app

COPY package*.json ./

RUN npm install --silent

COPY . .

RUN npm run build

FROM development As prod

ARG NODE_ENV=prod
ENV NODE_ENV=${NODE_ENV}

WORKDIR /user/src/app

COPY package.json ./

RUN npm install --prod

RUN npm install --only=prod