services:
  e2e21:
    build: 
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    networks:
      - nestjs-microservices
     
networks:
  nestjs-microservices:
    name: nestjs-microservices
    external: true